name: ctbench CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  clang:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch current branch
        uses: actions/checkout@v3
      - name: Compiling and running ctbench tests
        uses: ./.github/actions/run-tests
